### ISSUE TITLE
Possible problème de matching entre segm et yearmonth

### ISSUE THREAD

**Issue by luneauaymeric** [jphcoi/MADM#1]
Il  y a un petit soucis au niveau de la correspondance numéro de segment (segm) et yearmonth pour facebook et twitter (pas de soucis pour les média).
Exemple (voir impression écran ci-dessous)
2012-01 = segm 7.0 ; 2O12-02 = 0.0; 2012-03 = segm 6.0

![image](https://user-images.githubusercontent.com/103674633/163442215-58764365-4e28-464e-8bbb-195b06712699.png)

**Comment by jphcoi** [comment]
solved in the last commit
